import {
  GOOGLE_API_KEY,
  YELP_API_KEY,
  FIREBASE_API_KEY,
  AUTH_DOMAIN,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSAGING_SENDING_ID,
  APP_ID,
} from "@env";

export default {
  GOOGLE_API_KEY,
  YELP_API_KEY,
  FIREBASE_API_KEY,
  AUTH_DOMAIN,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSAGING_SENDING_ID,
  APP_ID,
};
